### ISSUE TITLE
NAO - coaching device

### ISSUE THREAD

**Issue by francescadag** [e-VITA/e-VITA-Platform-Issues#19]
Issues section relating to the NAO coaching device: reporting of problems, doubts in integration with e-VITA Platform, feedbacks, improvements.

**Comment by mehrboed** [comment]
There is an error on requests library.

Python: 2.7.3
openssl: 1.0.0f 4 Jan 2012
```
[ERROR] behavior.box :_safeCallOfUserMethod:281 _Behavior__lastUploadedChoregrapheBehaviorbehavior_1972167816__root__DigitalEnabler_2__Server_3__Digitalenabler_2: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/naoqi.py", line 269, in _safeCallOfUserMethod
    func(functionArg)
  File "<string>", line 27, in onInput_onStart
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 88, in post
    return request('post', url, data=data, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 383, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 486, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 385, in send
    raise SSLError(e)
SSLError: [Errno 1] _ssl.c:504: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
```

**Comment by JohannaCARITAS** [comment]
difficult for subject to assess whether NAO has recorded question or not

**Comment by mehrboed** [comment]
> difficult for subject to assess whether NAO has recorded question or not
Please check again with the newest update. Now, robot repeat what it understood.
